
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["prefab"]; }
        { if(!_buf["result"].IsString) { throw new SerializationException(); }  Result = _buf["result"]; }
        { if(!_buf["is_reserved"].IsBoolean) { throw new SerializationException(); }  IsReserved = _buf["is_reserved"]; }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// 主键，道具Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具图片icon
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 弹窗反馈效果描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 预制体
    /// </summary>
    public readonly string Prefab;
    /// <summary>
    /// 结果
    /// </summary>
    public readonly string Result;
    /// <summary>
    /// 道具夸关是否保留
    /// </summary>
    public readonly bool IsReserved;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "prefab:" + Prefab + ","
        + "result:" + Result + ","
        + "isReserved:" + IsReserved + ","
        + "}";
    }
}

}
