
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Puzzle : Luban.BeanBase
{
    public Puzzle(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["puzzle_name"].IsString) { throw new SerializationException(); }  PuzzleName = _buf["puzzle_name"]; }
        { if(!_buf["IsStart"].IsBoolean) { throw new SerializationException(); }  IsStart = _buf["IsStart"]; }
        { if(!_buf["next_id"].IsNumber) { throw new SerializationException(); }  NextId = _buf["next_id"]; }
        { var __json0 = _buf["init_item_list"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; InitItemList = new string[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  InitItemList[__index0++] = __v0; }   }
        { if(!_buf["suc_item"].IsString) { throw new SerializationException(); }  SucItem = _buf["suc_item"]; }
    }

    public static Puzzle DeserializePuzzle(JSONNode _buf)
    {
        return new Puzzle(_buf);
    }

    /// <summary>
    /// 主键，即关卡Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属谜题名
    /// </summary>
    public readonly string PuzzleName;
    /// <summary>
    /// 是否是初始关卡
    /// </summary>
    public readonly bool IsStart;
    /// <summary>
    /// 下一关卡Id
    /// </summary>
    public readonly int NextId;
    /// <summary>
    /// 关卡初始道具列表
    /// </summary>
    public readonly string[] InitItemList;
    /// <summary>
    /// 关卡正确道具id
    /// </summary>
    public readonly string SucItem;
   
    public const int __ID__ = -1892828066;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "puzzleName:" + PuzzleName + ","
        + "IsStart:" + IsStart + ","
        + "nextId:" + NextId + ","
        + "initItemList:" + Luban.StringUtil.CollectionToString(InitItemList) + ","
        + "sucItem:" + SucItem + ","
        + "}";
    }
}

}
